kind: project
metadata:
  name: tutorial-admin
spec:
  functions:
  - url: gen_iris.py
    name: gen-iris
    image: mlrun/mlrun
  - url: trainer.py
    name: trainer
    image: mlrun/mlrun
    handler: train
  - url: serving.py
    name: serving
    kind: serving
    image: mlrun/mlrun
  workflows: []
  artifacts: []
  source: ''
  subpath: ''
  origin_url: ''
  desired_state: online
  disable_auto_mount: false
